# Generated by Django 2.2.5 on 2019-09-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
                ('pf', models.PositiveIntegerField()),
                ('pa', models.PositiveIntegerField()),
                ('total_yards_offense', models.PositiveIntegerField()),
                ('total_offense', models.PositiveIntegerField()),
                ('pass_yards', models.PositiveIntegerField()),
                ('rush_yards', models.PositiveIntegerField()),
                ('ppg', models.FloatField()),
                ('pass_tds', models.PositiveIntegerField()),
                ('rush_tds', models.PositiveIntegerField()),
                ('first_downs', models.PositiveIntegerField()),
                ('total_yards_defense', models.PositiveIntegerField()),
                ('pass_yards_allowed', models.PositiveIntegerField()),
                ('rush_yards_allowed', models.PositiveIntegerField()),
                ('sacks', models.PositiveIntegerField()),
                ('forced_fumbles', models.PositiveIntegerField()),
                ('interceptions', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_owner', to='madden.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=2)),
                ('pass_yards', models.PositiveIntegerField(blank=True)),
                ('pass_td', models.PositiveIntegerField(blank=True)),
                ('pass_int', models.PositiveIntegerField(blank=True)),
                ('times_sacked', models.PositiveIntegerField(blank=True)),
                ('pass_complete', models.PositiveIntegerField(blank=True)),
                ('pass_attempt', models.PositiveIntegerField(blank=True)),
                ('rush_yards', models.PositiveIntegerField(blank=True)),
                ('rush_tds', models.PositiveIntegerField(blank=True)),
                ('fumbled', models.PositiveIntegerField(blank=True)),
                ('break_tackle', models.PositiveIntegerField(blank=True)),
                ('receptions', models.PositiveIntegerField(blank=True)),
                ('receiving_yards', models.PositiveIntegerField(blank=True)),
                ('receiving_tds', models.PositiveIntegerField(blank=True)),
                ('tackles', models.PositiveIntegerField(blank=True)),
                ('tfl', models.PositiveIntegerField(blank=True)),
                ('sacks', models.PositiveIntegerField(blank=True)),
                ('interceptions', models.PositiveIntegerField(blank=True)),
                ('defensive_tds', models.PositiveIntegerField(blank=True)),
                ('against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_played_against', to='madden.Owner')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='madden.Game')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='madden.Player')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_owner', to='madden.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('off_yards_gained', models.PositiveIntegerField()),
                ('rush_yards', models.PositiveIntegerField()),
                ('pass_yards', models.PositiveIntegerField()),
                ('first_downs', models.PositiveIntegerField()),
                ('punt_return_yards', models.PositiveIntegerField()),
                ('kick_return_yards', models.PositiveIntegerField()),
                ('against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_against', to='madden.Owner')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='madden.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_game_Stats', to='madden.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='lost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='madden.Owner'),
        ),
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='madden.Owner'),
        ),
    ]
