# Generated by Django 2.2.5 on 2019-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0002_auto_20190909_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
