# Generated by Django 2.2.5 on 2019-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0003_auto_20190909_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='turnovers',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
