# Generated by Django 2.2.5 on 2019-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0004_gamestat_turnovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
