# Generated by Django 2.2.5 on 2019-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0005_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='position',
        ),
    ]
