# Generated by Django 2.2.5 on 2019-09-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0006_remove_playerstat_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='turnovers',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='break_tackle',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='defensive_tds',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='fumbled',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='interceptions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_attempt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_int',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_td',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_yards',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='receiving_tds',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='receiving_yards',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='receptions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rush_tds',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rush_yards',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='sacks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='tackles',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='tfl',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='times_sacked',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
