# Generated by Django 2.2.5 on 2019-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0007_auto_20190909_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='turnovers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo_url',
            field=models.TextField(blank=True, default='blank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='break_tackle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='defensive_tds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='fumbled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='interceptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_complete',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_int',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_td',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_yards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='receiving_tds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='receiving_yards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='receptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rush_tds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rush_yards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='sacks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='tackles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='tfl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='times_sacked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
