# Generated by Django 2.2.5 on 2019-09-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0008_auto_20190909_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_game_stats', to='madden.Owner'),
        ),
    ]
