# Generated by Django 2.2.5 on 2019-09-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0010_auto_20190910_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestat',
            name='season',
        ),
        migrations.RemoveField(
            model_name='gamestat',
            name='week',
        ),
    ]
