# Generated by Django 2.2.5 on 2019-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0011_auto_20190910_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='season',
            field=models.PositiveIntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
