# Generated by Django 2.2.5 on 2019-09-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0013_auto_20190910_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='madden.Player'),
        ),
    ]
