# Generated by Django 2.2.5 on 2019-09-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0014_auto_20190910_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_game_stats', to='madden.Game'),
        ),
    ]
