# Generated by Django 2.2.5 on 2019-09-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0015_auto_20190910_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='madden.Owner'),
        ),
    ]
