# Generated by Django 2.2.5 on 2019-09-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0016_auto_20190910_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstat',
            name='coach_of_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='dboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='dloy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='dpoy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='koy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='lboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='mvp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='oloy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='opoy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='qboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='rboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='wroy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
