# Generated by Django 2.2.5 on 2019-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0017_auto_20190910_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lose_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='win_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
