# Generated by Django 2.2.5 on 2019-10-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0019_auto_20190911_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='forced_fumbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='pass_defended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='conference',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='division',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='droy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='oroy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='superbowl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='kick_return_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='pass_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='punt_return_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='rush_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='pass_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rush_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='sacks',
            field=models.FloatField(default=0),
        ),
    ]
