# Generated by Django 2.2.5 on 2019-10-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0021_seasonstat_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonstat',
            name='test',
        ),
    ]
