# Generated by Django 2.2.5 on 2019-10-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0022_remove_seasonstat_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestat',
            name='pass_yards',
        ),
        migrations.RemoveField(
            model_name='gamestat',
            name='rush_yards',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='defensive_tds',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='forced_fumbles',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='interceptions',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='pass_defended',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='sacks',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='tfl',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='coach_of_year',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='dboy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='division',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='dloy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='dpoy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='droy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='koy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='lboy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='mvp',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='oloy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='opoy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='oroy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='qboy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='rboy',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='superbowl',
        ),
        migrations.RemoveField(
            model_name='seasonstat',
            name='wroy',
        ),
    ]
