# Generated by Django 2.2.5 on 2019-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0023_auto_20191001_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='pass_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='rush_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='coach_of_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='conference',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='dboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='division',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='dloy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='dpoy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='droy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='koy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='lboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='mvp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='oloy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='opoy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='oroy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='qboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='rboy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='superbowl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstat',
            name='wroy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
