# Generated by Django 2.2.5 on 2019-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madden', '0024_auto_20191001_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='defensive_tds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='forced_fumbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='interceptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='pass_defended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='sacks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='tfl',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
